joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]

## control_mode_adapter
max_command_silence: 0.5

hardware_control_loop:
   loop_hz: 100

hardware_interface:
   joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

#Group Velocity Controller
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint

# Joint Trajectory Controller -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
joint_trajectory_controller:
   type: velocity_controllers/JointTrajectoryController
   joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
   constraints:
      goal_time: 0.5
      #stopped_position_tolerance: 0.4 # Defaults to 0.01
      arm_1_joint:
          trajectory: 0.1
          goal:       0.1
      arm_2_joint:
          trajectory: 0.1
          goal:       0.1
      arm_3_joint:
          trajectory: 0.1
          goal:       0.1
      arm_4_joint:
          trajectory: 0.1
          goal:       0.1
      arm_5_joint:
          trajectory: 0.1
          goal:       0.1
      arm_6_joint:
          trajectory: 0.1
          goal:       0.1
      arm_7_joint:
          trajectory: 0.1
          goal:       0.1
   gains:
       arm_1_joint: {p: 10.0,  i: 0.0, d: 0.01, i_clamp: 1}
       arm_2_joint: {p: 10.0,  i: 0.0, d: 0.01, i_clamp: 1}
       arm_3_joint: {p: 10.0,  i: 0.0, d: 0.01, i_clamp: 1}
       arm_4_joint: {p: 10.0,  i: 0.0, d: 0.01, i_clamp: 1}
       arm_5_joint: {p: 10.0,  i: 0.0, d: 0.01, i_clamp: 1}
       arm_6_joint: {p: 10.0,  i: 0.0, d: 0.01, i_clamp: 1}
       arm_7_joint: {p: 10.0,  i: 0.0, d: 0.01, i_clamp: 1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  25
   action_monitor_rate: 10


## compatibility section for old cob_trajectory_controller used with hardware ##
# trajectory controller parameters
frequency: 100 # Hz
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.1 # rad/sec^2
max_error: 5 # rad
